steps:
- name: 'gcr.io/cloud-builders/npm'
	args: ['i']
- name: 'gcr.io/cloud-builders/npm'
	args: ['test']
- name: 'gcr.io/cloud-builders/gcloud'
	args: ['functions', 'deploy', 'dataProcessor', '--retry', '--region', 'europe-west1', '--entry-point', 'processProductUpdate', '--runtime', 'nodejs8', '--trigger-topic', 'DW-product-update']

